doc/environment.rst, doc/index.rst
When running tests on different environments the environment specific settings need to be set in the `BEHAT_PARAMS` environment variable. This is not so straightforward so it would be nice to have documentation to help people with this.
This is my first foray into the wonders of the ReST text format and I have not yet found a good way of previewing this text so please forgive any formatting problems.
I have also rather shamelessly plugged my Drush extension that generates the environment variables automatically from the local environment.
=> Add documentation for environment specific settings

doc/_static/snippets/subcontext.inc, src/Drupal/DrupalExtension/Context/DrupalSubContextBase.php
It would be helpful if we provide a base class for subcontexts.
* Now all subcontexts have to implement the constructor but this is likely to be common for all subcontexts, causing code duplication.
* We can extend `RawDrupalContext` which would be a sane default for the most common case of subcontexts provided by contributed modules.
* If we have a base class we can also provide some helpful methods that can assist developers in building their subcontexts. As an example I have provided a method that allows the subcontext to get the currently logged in user from the DrupalContext class.
=> Provide a base class for subcontexts

src/Drupal/DrupalExtension/Context/DrupalSubContextInterface.php
`DrupalSubContextInterface` could use a little love:
* The docblock for the constructor is not correct, it uses the wrong parameter type for `$context`.
* it states that the constructor returns a string but a constructor cannot return any value since it returns the object itself.
* We can also add some documentation to help people understand its purpose.
=> Clean up DrupalSubContextInterface.

src/Drupal/DrupalExtension/Context/Environment/Reader/Reader.php
This is a followup for [Provide a base class for subcontexts](https://github.com/jhedstrom/drupalextension/pull/141). When the list of subcontext classes is compiled we should ignore the abstract ones to avoid Behat from trying to register them.
=> Do not register abstract subcontext classes.

features/field_handlers.feature, fixtures/drupal8/modules/behat_test/behat_test.install, fixtures/drupal8/modules/behat_test/behat_test.services.yml, fixtures/drupal8/modules/behat_test/src/Config/BehatTestExtensionInstallStorage.php
The current pull request adds test coverage for user field handling in Drupal 8 by enforcing Behat Test module's user entity configuration in Drupal 8 installation, so that feature steps can be tested properly.
=> Add test coverage for user field handling in Drupal 8

.travis.yml
This reverts commit ad9f0039832d4acd6c5b477c698557f0ca4c5ffd.
A temporary fix was committed to update the react/promise package on Travis until this was fixed upstream. Unfortunately the fix introduced a violation against the YAML standard which broke testing on Travis.
=> Issue #149: Revert "Temporary fix for Drupal 8 react/promise issue."

src/Drupal/Driver/Cores/CoreInterface.php, src/Drupal/Driver/Cores/Drupal6.php, src/Drupal/Driver/Cores/Drupal7.php, src/Drupal/Driver/Cores/Drupal8.php, src/Drupal/Driver/DrupalDriver.php
I'm still on 1.0, didn't check if this is already fixed in 3.0.
module_list() has been removed in 8.x, so the whole thing now depends on the core version, I moved it into the core drivers and added a new method for it.
=> Move building the extension list to the core driver

.travis.yml, fixtures/drupal8/modules/behat_test/config/install/field.field.user.user.field_user_tags.yml, fixtures/drupal8/modules/behat_test/config/install/field.storage.user.field_user_tags.yml, fixtures/drupal8/modules/behat_test/override_config/core.entity_view_display.user.user.default.yml
Attempt to simplify travis builds. These packages are supposedly all in the normal CI build.
=> Remove custom php package installation

src/Drupal/DrupalExtension/Context/DrupalContext.php
- Replaced `!$this->user->uid`with `!isset($this->user->uid)` which represses the notice and you will instead get the intended exception message.
=> "I am viewing my :type (content )with the title :title" generates notice on anonymous user

composer.json
I try to use another version of ``drupal/drupal-driver`` but the hardcoded branch name makes it unnecessary complicated.
=> Use branch alias instead of branch

features/d8.feature, src/Drupal/DrupalExtension/Context/DrupalContext.php
I tried to create a user without any additional roles, but it did not work because we cast empty string to array.
=> Allow users without roles

composer.json, features/language.feature, fixtures/drupal7/modules/behat_test/behat_test.info, fixtures/drupal8/modules/behat_test/behat_test.info.yml, src/Drupal/DrupalExtension/Context/DrupalContext.php, src/Drupal/DrupalExtension/Context/RawDrupalContext.php, src/Drupal/DrupalExtension/Hook/Scope/AfterLanguageCreateScope.php, src/Drupal/DrupalExtension/Hook/Scope/BeforeLanguageCreateScope.php, src/Drupal/DrupalExtension/Hook/Scope/LanguageScope.php
It would be nice if we could add support for testing languages. I'm using Behat for an internal Drupal platform that is used in the European Commission, and we are currently supporting 24 languages :)
This pull requests adds a step definition for enabling additional languages in tests:
```
Given the following languages are available:
| languages |
| en        |
| fr        |
| de        |
```
This is currently depending on my fork of Drupal Driver that adds the respective functionality for creating and deleting languages. The sister pull request for Drupal Driver is here: https://github.com/jhedstrom/DrupalDriver/pull/45
In case this is accepted we would need to revert commit 55f03a4 before merging this in. That commit points the Drupal Driver dependency to my own fork.
=> Add support for testing languages

doc/globalinstall.rst
I'm setting this up for the first time, and had to look around a bit to find out how to initialise behat since the globalinstall documentation doesn't specify that. We probably want to add that there.
The steps I followed were these: https://behat-drupal-extension.readthedocs.org/en/3.0/globalinstall.html
=> Add behat --init to the globalinstall documentation

src/Drupal/DrupalExtension/Context/DrupalContext.php
This is a very simple feature request. One of the most common actions is to log in as a user with a certain role:
```
@Given I am logged in as a user with the :role role(s)
```
I would love to have this shorter version available as an alias. This read and writes a bit more fluently :)
```
@Given I am logged in as a/an :role
```
=> Provide a shorter alias for logging in as a user with a certain role.

.travis.yml, behat.yml.dist, doc/_static/composer.json.d8, doc/localinstall.rst
This is a fix for issue #193. Adding the same version of Guzzle as Drupal 8 uses. This pulls in guzzle/psr7 version 1.2.0 as a dependency which contains a fix for the fatal error from #193.
This will still fail until https://www.drupal.org/node/2546272 is committed but that issue is RTBC and is on the brink of being committed. Awaiting this to be fixed upstream I'll create a fork of Drupal core with the patch applied to see whether we can get the tests green again.
Locally I had a test failure in the field handlers test, but that is probably unrelated to this issue.
=> Use the same version of Guzzle as Drupal 8 core.

doc/globalinstall.rst
When following the global install instructions to the letter I encountered an error at the last step.
The following error was displayed when I ran the behat -dl command:
[Behat\Behat\Context\Exception\ContextNotFoundException]
`FeatureContext` context class not found and can not be used.
Moving the FeatureContext.php file from /behat-tests/features/bootstrap to /behat-tests fixed the issue for me.
Hopefully this will be helpful to others.
=> Update globalinstall.rst re `FeatureContext` not found error/

src/Drupal/DrupalExtension/Context/DrupalContext.php
The characters present in Random.string make the Pantheon security sniffer suspicious when they pass through the [Behat Drush Endpoint](https://github.com/drush-ops/behat-drush-endpoint).
Perhaps it would be sufficient to simplify here?  This change shouldn't affect the robustness of the tests; if users specifically want to test certain characters in node creation, they could always explicitly use them in their test data.
Hope this is okay.
=> Use Random.name instead of Random.string for node and taxonomy content.

.travis.yml
Former logic did not correctly set $? after test failures, so failing builds were mistakenly marked as passing.
We had:
test $v -eq 7 && behat || true
So, if $v was NOT 7, then the test returns false, and we need the `|| true` clause to prevent a spurious failure for the skipped test.  However, if $v IS 7, then the `|| true` clause runs regardless of the outcome of the behat test, so $? is always 0.
I changed this to:
test \! $v -eq 7 || behat
Now, if $v is NOT 7, then the test returns true, and processing stops, correctly skipping the test without marking it as an error.  If $v IS 7, then test returns false, and behat runs.  $? is set based on the outcome of the test.
Right now, the drupalextension tests are failing (my fault), but are being marked as successful due to this logic error. …
=> Fix comparisons in tests; 

composer.json, src/Drupal/DrupalExtension/ServiceContainer/config/drivers/drupal.yml, src/Drupal/DrupalExtension/ServiceContainer/config/drivers/drush.yml, src/Drupal/DrupalExtension/ServiceContainer/config/services.yml
Pull request for #225.
On recent build jobs the following error occurs:
```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                   
The file "src/Drupal/DrupalExtension/ServiceContainer/config/services.yml" does not contain valid YAML.
[Symfony\Component\Yaml\Exception\ParseException]                                                                           
The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 37 (near "- @drupal.random").
```
Starting in Symfony/Yaml 3.0 strings starting with an '@' need to be quoted.
=> Compatibility with Symfony 3.0

src/Drupal/DrupalExtension/Context/RawDrupalContext.php
This PR should address the usability and PHP error found in #227 
The check for a logged-in user is the same as Drupal's SimpleTest, which is the existence of a "log_out" link. I think it's fair to continue to look for that, but the error today doesn't describe the problem and has a PHP error if certain conditions are met.
Current:
> Failed to log in as user '%s' with role '%s'
Proposed solution:
> Unable to determine if logged in because 'log_out' link cannot be found for user '%s' with role '%s'
That way, developers know why the test is failing rather than something that implies that there's a problem with roles (there isn't).
Also, there's a PHP error if `$this->user->role` is missing, which was being experienced if you attempt to log in with permissions, not roles, which is why I'm …
=> Improve verbosity of login failure.

.travis.yml, features/drush.feature
Add a failing test demonstrating that the Drush driver cannot create content without the Behat Drush Endpoint.
Next will come working tests.
=> Drush tests

doc/_static/composer.json.d8, features/api.feature, features/field_handlers.feature, src/Drupal/DrupalExtension/Context/DrupalContext.php, src/Drupal/DrupalExtension/Context/RawDrupalContext.php
Currently the test coverage in `features/api.feature` mainly covers Drupal 7, but looking through the tests all this functionality should already be present in the D8 driver. Let's enable as many tests for Drupal 8 as are feasible.
=> [WIP] Extend test coverage for the D8 API and fix any uncovered problems

composer.json, doc/_static/composer.json.d8, features/bootstrap/FeatureContext.php, features/field_handlers.feature
Recently support was added to Behat to do @transform on row-based tables: [PR #654: Add support for row table transformations](https://github.com/Behat/Behat/pull/654). This finally makes it possible to use human readable names for fields.
Up to now we were forced to use machine names which are not only ugly, but violate the BDD principle of using domain specific language:
```
When I am viewing a "post" content:
| title                | Post title          |
| body                 | Body text           |
| field_post_reference | Page one, Page two  |
| field_post_date      | 2015-02-08 17:45:00 |
```
```
When I am viewing a "post" content:
| title     | Post title          |
| body      | Body text           |
| reference | Page one, Page two  |
| date      | 2015-02-08 17:45:00 |
``` …
=> Provide an example that uses human readable field names

src/Drupal/DrupalExtension/Context/MessageContext.php, src/Drupal/DrupalExtension/Context/RawDrupalContext.php, src/Drupal/DrupalExtension/ServiceContainer/DrupalExtension.php
Based heavily on https://github.com/jhedstrom/drupalextension/pull/131
This makes Drupal 7 work for themes without logout link on front-page and also makes Drupal 8 minimal profile, which uses stark work.
For most cases it can also avoid the visit to an additional page, which is great.
Not all websites have the logout link on the front page, in my case, Chrome with Selenium was simply to fast, admin-menu showed up after the check for the link happened.
Since there is no real 100% reliable method in D7, I've implemented two more methods to determine if a user is logged in. (D8 has the user information in the global Drupal Javascript object)
First test: Check for a "logged-in" class on the body element, most themes support this. (Mothership for example doesn't)
Second test: Visit …
=> Use better technique to determine whether user is logged in #131

src/Drupal/DrupalExtension/Context/DrupalContext.php
The `$link` variable is reused in `DrupalContext::assertClickInTableRow()` causing the exception text to lack the link text when it is thrown:
> Found a row containing "Article", but no "" link on the page http://drupal.local/admin/structure/types (Exception)
=> Missing link text in the exception thrown in DrupalContext::assertClickInTableRow()

composer.json
Version 3.1.0-rc1 contains the fix for PR #801 that we needed. We no longer need to track the development branch now.
=> There is a new release candidate for Behat.

src/Drupal/DrupalExtension/Context/MinkContext.php
We have an `assertButton()` method to check if a form submit button is present on the page, but its counterpart `assertNotButton()` is missing.
=> Add an assert to check if a button is not present on the page.

.travis.yml, doc/_static/composer.json.d8
The previous fix in #256 was hitting rate limits on github. This should only perform the install once.
=> Update tests to run against 8.1.x

.travis.yml, composer.json, doc/_static/composer.json.d8
Drupal 8.1 is going to be released soon. It's using Symfony 2.8. We need to update our dependencies to support this, or this will cause conflicts in projects that depend both on Drupal core and Drupal extension. One example is my fork of Drupal-project: https://github.com/pfrenssen/drupal-project.
=> Add support for Drupal 8.1.

src/Drupal/DrupalExtension/Context/DrupalContext.php
Currently, the existing breakpoint function in DrupalContext waits on a carriage return key to continue.  If you're using this breakpoint to inspect a particular test, and you wish to exit after you have determined the test has failed, the existing method offers no option for it.  You could use Ctrl+C (on POSIX), but in my experience, db cleanup operations are improperly handled after a SIGINT.
This change side-steps the problem by throwing an exception after a 'q' entry by the user.  This in turn results in a test exit with a proper cleanup.
=> Add a quit handler to breakpoint

src/Drupal/DrupalExtension/Context/RawDrupalContext.php
When using scenario outlines and a logged in user, the user gets invalid on the second run of the oultine, as @afterScenario deletes all created users. The proposed fix invalidates the user-property and logs the user out.
=> Fix scenario outline #288

features/blackbox.feature, features/bootstrap/FeatureContext.php, features/d8.feature, spec/Drupal/DrupalExtension/Context/Initializer/DrupalAwareInitializerSpec.php, src/Drupal/DrupalExtension/Context/DrupalAwareInterface.php, src/Drupal/DrupalExtension/Context/DrupalContext.php, src/Drupal/DrupalExtension/Context/DrupalSubContextBase.php, src/Drupal/DrupalExtension/Context/Initializer/DrupalAwareInitializer.php, src/Drupal/DrupalExtension/Context/RawDrupalContext.php, src/Drupal/DrupalExtension/ServiceContainer/config/services.yml, src/Drupal/DrupalUserManager.php, src/Drupal/DrupalUserManagerInterface.php
This is a proof of concept for #306.
I have created a very simple `DrupalUserManager` service that has a getter and setter for the current user object. This allows to persist the logged in user and share it between the different contexts that all extend `RawDrupalContext`.
In order to make this work with existing code that accesses the `RawDrupalContext::$user` property directly I'm hijjacking it with a magic getter and setter. This should in theory be compatible with all  existing 3.x code, but let's have a look at how this affects the current test suite first :)
Now that we have a 4.x branch I'd love to go a bit further. We can get rid of all code that directly accesses `RawDrupalContext::$user` and `RawDrupalContext::$users`, and replace it with this service.
=> Make the current user available in all contexts.

src/Drupal/DrupalExtension/Context/MessageContext.php
I am using an `@AfterStep` to take screenshot if I have PHP notices on the screen. I suddenly noticed this started taking screenshots of every step, even if there were no PHP notices.
This was because I was checking the notices with the MessageContext, and somewhere in the chain an exception was thrown. My code could not distinguish between an actual failed message and an unrelated exception:
```
try {
$context->assertNotWarningMessage('Notice:');
}
catch (\Exception $e) {
$this->saveScreenshot();
}
```
Let's use a more specific exception to indicate that our expectation was not met.
Note that this is a potential B/C break with the current code base in the 3.x branch. If people have been using code like in this example snippet, then they won't be able to catch messages any more.
=> Use a more specific exception to indicate unmet expectations in MessageContext

.travis.yml, behat.yml.dist, features/blackbox.feature, fixtures/blackbox/community.html, fixtures/blackbox/download.html, fixtures/blackbox/form.html, fixtures/blackbox/index.html, fixtures/blackbox/irc.html, fixtures/blackbox/user.html
=> Test blackbox scenarios against a static HTML site

features/bootstrap/FeatureContext.php
There have been a few occasions where tests have failed on Travis due to collisions of the random name that is generated for the test folder. The most recent of this occurred in https://travis-ci.org/jhedstrom/drupalextension/jobs/189521981
Let's generate another random name if the folder already exists.
=> Avoid random failures due to collisions in random directory names

src/Drupal/DrupalExtension/Context/MinkContext.php
=> BeforeStep and AfterStep no longer support tags in Behat 3

features/field_handlers.feature, src/Drupal/DrupalExtension/Context/RawDrupalContext.php
Resolves #346.  Not sure this is right yet, let's see what the tests say..
=> Blanks in entity tables

doc/_static/snippets/composer.json
- `~3.0` conflicts with phpunit ^6.1
=> Changed drupalextension version for Drupal 7

doc/_static/snippets/composer.json.d8
- `~3.0` conflicts with phpunit ^6.1
=> Changed drupalextension version for Drupal 8

.travis.yml
PHP 5.3 has become unsupported years ago. Our test suite has been failing on the 5.3 tests for over a year now. This is slowing down the test runs.
Instead of spending time trying to fix it, let's just remove it from the matrix and move on.
=> Stop testing on PHP 5.3

.travis.yml
In PR #324 we are making sure BDE is compatible with the latest versions of Behat and Symfony components. These no longer support PHP 5.4, so let's stop testing that version.
=> Stop testing on PHP 5.4

doc/_static/snippets/behat-sub.yml, doc/subcontexts.rst
Document the `paths:` key in `behat.yml` to run tests located in contributed/custom modules.
=> Document the `paths:` key in `behat.yml` to run tests located in contributed modules

README.md, composer.json, features/bootstrap/FeatureContext.php, src/Drupal/DrupalExtension/Context/Environment/Reader/Reader.php, src/Drupal/DrupalExtension/Context/RawDrupalContext.php
I just noticed in our project we were stuck on an old release of Behat, while the new 3.2.2 version was released a couple of days ago. Seems like we forgot to update our dependencies when 3.1.0 was released back in March.
=> Revert to stable release of Behat

src/Drupal/DrupalExtension/Context/DrupalSubContextBase.php
This PR introduces a new exception that should help developers understand under which circumstances contexts cannot be retrieved.
This is a DX improvement that is inspired by issue #386.
=> Throw an exception when the environment is not yet initialized

spec/Drupal/DrupalExtension/Listener/DriverListenerSpec.php, src/Drupal/DrupalExtension/Listener/DriverListener.php
I discovered a big ol' bug today!
During the environment isolation process, Behat's ContextEnvironmentHandler class will, in its isolateEnvironment() method, convert UninitializedContextEnvironment to InitializedContextEnvironment, which is necessary in order for any Drupal Extension subcontext's getContext() method to work.
Unfortunately, during scenario outline tests, Drupal Extension does not pick up the new environment, so any calls to getContext() in scenario examples results in a fatal error (call to undefined getContexts() method in UninitializedContextEnvironment). This is because the OutlineTested::BEFORE event is fired *before* Behat isolates the environment.
The fix, I discovered, is for Drupal Extension's DriverListener to react to the ExampleTested::BEFORE event instead of …
=> DriverListener should react to ExampleTested events

src/Drupal/DrupalExtension/Context/DrupalContext.php, src/Drupal/DrupalExtension/Context/RawDrupalContext.php, src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php, src/Drupal/DrupalExtension/Manager/FastLogoutInterface.php
This addresses #62 and includes the logout hardening commit from #393.
=> Logout performance

src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php
=> #446 Check for session first before logging out in fastLogout method of DrupalAuthenticationManager

features/i18n/es/blackbox.feature, features/i18n/es/d8.feature, features/i18n/es/language.feature, fixtures/blackbox/assertRegionElementAttribute.html, i18n/es.xliff
Steps translated:
* the/these (following )languages are available:
* users:
* I should see (the text ):text in the :rowText row
* I should not see (the text ):text in the :rowText row
* I am logged in as a/an :role
* I (should ) see the button :button
* I (should ) see the :button button
* I should not see the button :button
* I should not see the :button button
* I should see the button :button in the :region( region)
* I should see the :button button in the :region( region)
* I( should) see the :tag element in the :region( region)
* I( should) not see the :tag element in the :region( region)
* I( should) not see :text in the :tag element in the :region( region)
* I( should) see the :tag element with the :attribute attribute set to :value in the :region( region)
* I( should) see :text in …
=> drupalExtension is fully translated to Spanish

.travis.yml, composer.json
Drush 9 is now out, so this needs to happen even if we stop testing the drush behat endpoint until it is ported.
- Fixes #419
=> Test Drupal 8 with Drush 9.

doc/globalinstall.rst
Composer maintainers strongly advise against running composer as sudo/root. On Mac and Ubuntu it appears not to be necessary. Is it possible to accomplish everything without using sudo with composer?
See their FAQ:
How do I install untrusted packages safely? Is it safe to run Composer as superuser or root?
https://getcomposer.org/doc/faqs/how-to-install-untrusted-packages-safely.md
=> remove sudo from composer command

.travis.yml, composer.json
- Allows higher phpspec version
- Removes unused phpunit requirement
- Fixes #474
=> Use a 'test' script for running tests.

src/Drupal/DrupalExtension/Context/MinkContext.php
Very rough, just as a proof-of-concept, but this seems to help a lot while troubleshooting where a given error is coming from.
=> #479: Provide more verbose exception message when AJAX fails.

behat.yml.dist, doc/contexts.rst, features/random.feature, spec/Drupal/DrupalExtension/Context/RandomContextSpec.php, src/Drupal/DrupalExtension/Context/RandomContext.php
```
Given I am viewing an "Article" with the title "<title>"
Then I should see the header "<title>"
```
When the `RandomContext` is included, then `<title>` will be replaced
with a random string during the scenario. It will have a consistent
value throughout a given scenario, but a new value in subsequent
scenarios.
- Fixes #293
=> Adds a RandomContext for generating random strings in steps.

composer.json, src/Drupal/DrupalExtension/Context/RawDrupalContext.php
=> Fix coding standards.

.travis.yml
When PHP 7.1 was initially released there were some incompatibilities for Drupal 7 and we temporarily allowed this to fail on Travis. In the meantime D7 works fine on PHP 7.1 and we have a green build!
Let's support this combo from now on.
=> Start supporting Drupal 7 on PHP 7.1

src/Drupal/DrupalExtension/ServiceContainer/DrupalExtension.php
The default `login_form_selector` is using `form#user-login` as a selector, but the actual drupal login form (at least for current d8) uses `form#user-login-form` as the id. My guess is an update to underlying form changed this at some point (maybe during migration to drupal 8?)? 
This can ultimately cause false positives from `RawDrupalContext::loggedIn()` - in some scenarios the login is validated by manually checking the  `/user/login` page and looking for the form via this selector - if its not found, the user is assumed to be logged in. In this case even though the user is anonymous, the form is not found, so it returns true. 
I left the old selector in for any possible BC issues, similar to how the `logged_in_selector` works. 
For example, here's a blank site spun up w/ …
=> RawDrupalContext::loggedIn() can return false positive

features/field_handlers.feature, fixtures/drupal7/modules/behat_test/behat_test.features.field_base.inc, fixtures/drupal8/modules/behat_test/config/install/field.storage.node.field_post_select.yml
- Changes to test compatiblity with https://github.com/jhedstrom/DrupalDriver/issues/168
It's odd these scenarios were previously passing--the actual field value being saved on the node was `One`, rather than the field key of `1` and `2`.
=> Corresponding list handler fixes for the Drupal Driver.

features/blackbox.feature, src/Drupal/DrupalExtension/Context/MarkupContext.php
There is already a step in `MarkupContext` to assert that a button exists within a region but not one to assert that one does not exist. Here is a small patch.
=> Provide a step to check that a button is not in a region.

CHANGELOG.md, README.md, behat.yml.dist, doc/environment.rst, features/subcontexts/find.feature, src/Drupal/DrupalExtension/Context/MinkContext.php
In https://github.com/jhedstrom/drupalextension/issues/486#issuecomment-459487280 @leevh mentioned that the AJAX timeout won't work if the user has made a mistake in the configuration and used `Behat\MinkExtension` instead of our overridden `Drupal\MinkExtension`.
This is a very easy mistake to make, especially when considering that our documentation for versions 3.x and lower of DrupalExtension suggests to use `Behat\MinkExtension` instead of `Drupal\MinkExtension`. This is also suggested in a number of blog posts and stack overflow answers. Also people upgrading from 3.x will likely hit this bug.
This can be quite insidious, since everything will seem to work as normal, but when the `@javascript` tag is being used then suddenly mysterious failures will pop up: "Unable to complete AJAX …
=> Throw a helpful exception if the AJAX timeout is missing

doc/blackbox.rst, src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php, src/Drupal/DrupalExtension/ServiceContainer/DrupalExtension.php
Inspired by https://www.drupal.org/project/drupalextension/issues/2958158
In certain circumstances it can be a good idea to change the standard drupal login path (ie: for security improvements).
In that case, the Drupal Behat extension will not be able to log in to the standard /user URL.
I've developed a little patch that adds a further configuration option to specify custom login/logout URL.
=> Adding the option to specify a custom login/logout path in your behat.yml

CHANGELOG.md, src/Drupal/DrupalExtension/Context/Environment/Reader/Reader.php
=> Deprecate subcontexts in Drupal Behat Extension 4.0.0.

src/Drupal/DrupalExtension/Context/MinkContext.php
Trying to fix jhedstrom#560.
Maybe there is a better way.
=> Add space arround the keywords to avoid wrongly matching.

.travis.yml, composer.json
Same as https://github.com/jhedstrom/DrupalDriver/pull/222
=> Allow Symfony 4 as dependency

src/Drupal/DrupalExtension/Context/MailContext.php
Since Gherkin 4.9.0 tags with whitespace are deprecated: use a comma as an explicit OR operator.
See
- https://github.com/Behat/Gherkin/issues/213
- https://github.com/Behat/Gherkin/pull/215
- https://behat.org/en/latest/user_guide/context/hooks.html#tagged-hooks
Closes #600
Thanks!
=> #600: Avoid whitespace in tags 

CONTRIBUTING.md, README.md
Same as https://github.com/jhedstrom/DrupalDriver/pull/258
=> Document local test usage

src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php
OK, so I have a use case it's kind of convoluted to achieve at the moment.
The login method will fill in fields and submit the form to log in. If for some reason you have changed the default markup, you can override the way this is selected by providing a value for the "drupal text" `log_in`.
This is convenient if you use English, and only that. That way you could probably add "Log in" and be done with it. If you want to accommodate that the site can theoretically at different stages have this part translated, or not, then using the string for the value of the submit is not so convenient. Luckily, we use the method `findButton` which does this:
```
/**
* Finds button (input[type=submit|image|button|reset], button) with specified locator.
*
* @param string $locator button id, value or alt …
```
=> Add a helper for the getting of the login submit element

.github/workflows/ci.yml, CHANGELOG.md, README.md, behat.yml.dist, composer.json, docker-compose.yml, features/d8.feature, features/i18n/es/d8.feature, src/Drupal/MinkExtension/ServiceContainer/Driver/BrowserKitFactory.php
Behat tests are failing for logged in users when the site is accessed via HTTPS and SSL peer verification is failing. But with `BrowserTestBase` we're able to run such tests. Testing should not require a valid SSL certificate
Make Guzzle request options configurable
Example:
```yaml
default:
suites:
default:
contexts:
- FeatureContext
- Drupal\DrupalExtension\Context\DrupalContext
- Drupal\DrupalExtension\Context\MinkContext
extensions:
Drupal\MinkExtension:
base_url: https://localhost
browserkit_http:
guzzle_request_options:
verify: false
```
In this example, `browserkit_http.guzzle_request_options` is configured to instantiate the Guzzle underlying HTTP client with the `verify` request option set to `false`, same as `BrowserTestBase:: initMink()` is doing
=> Make Guzzle request options configurable

src/Drupal/DrupalExtension/ServiceContainer/DrupalExtension.php
PHP 8.4 is showing a deprecation warning:
```
PHP Deprecated:  Drupal\DrupalExtension\ServiceContainer\DrupalExtension::__construct(): Implicitly marking parameter $processor as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/ServiceContainer/DrupalExtension.php on line 42
```
I ran a check with rector and it found only one case in the whole codebase.
=> Fix php 8.4 deprecation

src/Drupal/DrupalExtension/Context/RawDrupalContext.php
In PHP 8.4 we have this warning:
```
Deprecated: str_getcsv(): the $escape parameter must be provided as its default value will change in /var/www/html/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/RawDrupalContext.php line 425
```
To avoid this warning, we should explicitly pass the escape parameter.
=> Fix deprecation notice in PHP 8.4 with function str_getcsv

composer.json
In a previous PR, the deps from Symfony were updated, but http-client is forcing to stay in Symfony 6, which prevents to go to Drupal 11.
=> Upgrade symfony/http-client to compatibility with Symfony 7
