jhedstrom/drupalextension

doc/_static/snippets/api.feature

see https://www.drupal.org/node/2403629

replaced "nodes" with "content" in example feature

---

src/Drupal/Driver/Cores/Drupal8.php

Same changes as in your DrupalCores repository

Update Drupal 8 bootstrap

---

src/Drupal/DrupalExtension/Context/BatchContext.php

@jhedstrom following up on https://github.com/jhedstrom/drupalextension/pull/136 - is this what you meant?
I am still on Behat 2.5 so I am not sure that I can test this.

Add BatchContext

---

.travis.yml
behat.yml.dist
features/api_background.feature

Let's try to get a nice build matrix up and running so we can test different Drupal versions on different PHP versions.

A build matrix for Travis CI

---

doc/intro.rst

Cleaned up formatting for the list

Update the rst

---

src/Drupal/DrupalExtension/Context/MarkupContext.php

This solves Issue #162 and https://www.drupal.org/node/2488352

Issue #162 Step not comparing attribute against :value argument.

---

doc/_static/snippets/subcontext.inc

Adding documentation for context communication.

---

.travis.yml
features/bootstrap/FeatureContext.php
src/Drupal/DrupalExtension/Context/RawDrupalContext.php

Support PHP 5.3

---

src/Drupal/DrupalExtension/Context/MinkContext.php

Reverts jhedstrom/drupalextension#171

Revert "Update assertSelectRadioById"

---

doc/drivers.rst
doc/drush.rst

Here are some updates to the docs to describe the recent improvements in the Drush Driver.

Update documentation on the Drush Driver for the Behat Drush Endpoint.

---

features/drush.feature
src/Drupal/DrupalExtension/Context/DrushContext.php

Just a simple new step definition for matching drush output with regex, and a simple test to go with it.

Adds drush output regex matching

---

composer.json
doc/_static/composer.json.d8

Upgrade to Behat 3.1.0-rc2

---

.travis.yml

Pin behat-drush-endpoint to use symfony 2.x

---

behat.yml.dist
features/config.feature
src/Drupal/DrupalExtension/Context/ConfigContext.php
src/Drupal/DrupalExtension/Context/DrupalContext.php
src/Drupal/DrupalExtension/Context/RawDrupalContext.php

Depends on https://github.com/jhedstrom/DrupalDriver/pull/76
Provides 2 step definitions, one to update basic config, one for more complex config (i.e arrays)

Configuration change step definitions for D8

---

doc/_static/snippets/drush.feature

The bottom two Scenarios are redundant to the first two.

Redundant Scenarios

---

.travis.yml
behat.yml.dist
features/messages.feature

Test Drupal 8 with big_pipe enabled

---

features/api.feature
features/d8.feature
src/Drupal/DrupalExtension/Context/DrupalContext.php

Provides "not in row" step definition and tests

---

behat.yml.dist
features/blackbox.feature

More fixes for the blackbox tests.wq

---

.travis.yml
features/bootstrap/FeatureContext.php

To my great delight PHP 7.1 has been released. Let's make sure our software runs on this sweet new version :)

Run tests also on the newly released PHP 7.1

---

doc/_static/snippets/api.feature

Doc fix for term references

---

src/Drupal/DrupalExtension/Context/DrupalContext.php

Do not assume nodes of all types have 'body' fields

---

features/api.feature
features/field_handlers.feature
src/Drupal/DrupalExtension/Context/RawDrupalContext.php

Allow field values that include a comma by wrapping them in double quotes

---

src/Drupal/DrupalExtension/Context/RawDrupalContext.php

At the start of a webdriver session the user is not logged in.

---

features/bootstrap/FeatureContext.php

Add missing import for 3.3 version

---

src/Drupal/DrupalExtension/Context/RawDrupalContext.php

The user is anonymous if the session has not yet been started

---

src/Drupal/DrupalExtension/Context/MinkContext.php

Use wait on ajax logic from Drupal 8

---

src/Drupal/DrupalExtension/Context/DrupalContext.php

This PR addresses #361. Pretty straightforward! Not sure how, or if, I should add tests for this...? Please advise.
Let's get v3.3.1 out. acquia/lightning needs it :)

Allow spaces between permissions

---

.travis.yml
composer.json

Use php parallel lint

---

src/Drupal/DrupalExtension/ServiceContainer/config/drivers/blackbox.yml
src/Drupal/DrupalExtension/ServiceContainer/config/drivers/drupal.yml
src/Drupal/DrupalExtension/ServiceContainer/config/drivers/drush.yml
src/Drupal/DrupalExtension/ServiceContainer/config/services.yml

Pull request for https://github.com/jhedstrom/drupalextension/issues/423

#423 Quoted all usages of '%' in the YAML files

---

spec/Drupal/DrupalExtension/Context/Initializer/DrupalAwareInitializerSpec.php
src/Drupal/DrupalExtension/Context/DrupalAwareInterface.php
src/Drupal/DrupalExtension/Context/Initializer/DrupalAwareInitializer.php
src/Drupal/DrupalExtension/Context/RawDrupalContext.php
src/Drupal/DrupalExtension/DrupalParametersTrait.php
src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php
src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManagerInterface.php
src/Drupal/DrupalExtension/Manager/DrupalUserManager.php
src/Drupal/DrupalExtension/Manager/DrupalUserManagerInterface.php
src/Drupal/DrupalExtension/MinkAwareTrait.php
src/Drupal/DrupalExtension/ServiceContainer/config/services.yml

Continuation of #339 and #393. This does not contain the logout hardening commit from #393 as I think that can be a separate issue.

Create an AuthenticationManager service

---

src/Drupal/DrupalExtension/Context/DrupalSubContextBase.php
src/Drupal/DrupalExtension/Context/RawDrupalContext.php

Reroll: move getContext into RawDrupalContext

---

src/Drupal/DrupalExtension/Context/MinkContext.php

Reroll: ajax fix for d7

---

features/blackbox.feature
fixtures/blackbox/assertRegionElementAttribute.html
src/Drupal/DrupalExtension/Context/MarkupContext.php

reroll: fix issue #406 assertRegionElementAttribute

---

i18n/fr.xliff

reroll: Do the French translation of fr.xliff

---

doc/environment.rst

This targets #359 against `master`.

reroll: Fix code block.

---

src/Drupal/DrupalExtension/Context/DrupalContext.php

reroll: Undesirable PHP Notice displayed when Exception thrown

---

src/Drupal/DrupalExtension/Context/MinkContext.php

Merged latest `master` into #302.

Reroll: In step to select Radio button, look for label explicitly by ID instead of parent()

---

src/Drupal/DrupalExtension/ServiceContainer/config/services.yml

scalar value quotes

---

README.md
composer.json

Adds authors and maintainers to the README and composer.json

---

src/Drupal/DrupalExtension/Context/RawDrupalContext.php

Further use of fast logout.

---

i18n/es.xliff

little PR to reference issue #444 in code

reference to #444 in code

---

composer.json

Lock DrupalDriver to the latest stable release

---

CHANGELOG.md
README.md
behat.yml.dist
composer.json
doc/_static/snippets/behat-1.yml
doc/_static/snippets/behat-api.yml
doc/_static/snippets/behat-auto.yml
doc/_static/snippets/behat-bb.yml
doc/_static/snippets/behat-drush.yml
doc/_static/snippets/behat-sub.yml
spec/Drupal/MinkExtension/ServiceContainer/MinkExtensionSpec.php
src/Drupal/DrupalExtension/Context/MinkContext.php
src/Drupal/MinkExtension/ServiceContainer/MinkExtension.php

Allows AJAX timeout to be overridden.

---

src/Drupal/DrupalExtension/Context/DrupalContext.php

Per discussion here:
https://www.drupal.org/project/drupalextension/issues/2949532#comment-12507525

Adding simple logout context

---

.travis.yml
composer.json

Update pinned dependency injection version for latest Drupal.

---

CHANGELOG.md

Adds notable changes to CHANGELOG.md.

---

.travis.yml

Require drupal-driver for global drush install.

---

src/Drupal/DrupalExtension/Context/MinkContext.php
src/Drupal/DrupalExtension/ScenarioTagTrait.php

- Fixes #468 
I found a proper workaround over in https://github.com/Behat/Behat/issues/703#issuecomment-86687563, and have added that here as a trait.

Adds a trait for determining current scenario tags.

---

.gherkin-lintignore
.gherkin-lintrc
.gitignore
composer.json
features/api.feature
features/api_background.feature
features/blackbox.feature
features/d6.feature
features/d8.feature
features/drush.feature
features/field_handlers.feature
features/mail.feature
features/messages.feature
features/subcontexts/find.feature
package.json

- Fixes #504
- Fixes inconsistencies in the `.feature` files included for testing.

Add gherkin-lint to the build process.

---

.travis.yml

Remove patch to Features module that has been committed.

---

.travis.yml

Travis changed composer global directory: https://github.com/travis-ci/travis-ci/issues/7289#issuecomment-427333966

Update composer path.

---

.travis.yml
CHANGELOG.md
composer.json
features/drush.feature

Drupal 8 now requires PHP 7 or greater.

---

.gitignore
.travis.yml
CHANGELOG.md
README.md
behat.yml.dist
composer.json
features/blackbox.feature
features/i18n/es/blackbox.feature
features/messages.feature
package.json

* Adds gherkin-lint to feature files on Travis
* Adds a Contributing section to the README
* Removes zombie js testing
* Closes #545 
* Closes #544 
* Closes #543

Remove Zombie JS from Travis CI

---

CHANGELOG.md
doc/_static/snippets/FeatureContext.php.inc
src/Drupal/DrupalExtension/Context/ContextClass/ClassGenerator.php

SnippetAcceptingContext is deprecated.

---

.travis.yml
composer.json

Remove requirement for specific event dispatcher.

---

CHANGELOG.md
composer.json
features/backend_login.feature
features/bootstrap/FeatureContext.php
src/Drupal/DrupalDriverManager.php
src/Drupal/DrupalDriverManagerInterface.php
src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php
src/Drupal/DrupalExtension/ServiceContainer/config/services.yml

- Fixes #488 
This could use some testing, especially from folks using alternative authentication managers.
The corresponding driver PR is at https://github.com/jhedstrom/DrupalDriver/pull/187

Authenticate user in the backend bootstrap process on login.

---

CHANGELOG.md
spec/Drupal/DrupalDriverManagerSpec.php
spec/Drupal/DrupalExtension/Context/DrupalContextSpec.php
spec/Drupal/DrupalExtension/Context/DrushContextSpec.php
spec/Drupal/DrupalExtension/Context/Initializer/DrupalAwareInitializerSpec.php
spec/Drupal/DrupalExtension/Context/RandomContextSpec.php
spec/Drupal/DrupalExtension/Context/RawDrupalContextSpec.php
spec/Drupal/DrupalExtension/Hook/Scope/BeforeNodeCreateScopeSpec.php
spec/Drupal/DrupalExtension/Listener/DriverListenerSpec.php
spec/Drupal/DrupalExtension/Manager/DrupalAuthenticationManagerSpec.php
spec/Drupal/DrupalExtension/Manager/DrupalUserManagerSpec.php
spec/Drupal/DrupalExtension/Selector/RegionSelectorSpec.php
spec/Drupal/DrupalExtension/ServiceContainer/DrupalExtensionSpec.php
src/Drupal/DrupalExtension/Context/DrupalAwareInterface.php
src/Drupal/DrupalExtension/Context/RandomContext.php
src/Drupal/DrupalExtension/Context/RawDrupalContext.php
src/Drupal/DrupalExtension/Listener/DriverListener.php
src/Drupal/DrupalExtension/Manager/DrupalUserManager.php
src/Drupal/DrupalExtension/Manager/DrupalUserManagerInterface.php

- Changed to use interfaces for type-hinting where necessary.
- Closes #565

Improve PHPSpec coverage.

---

README.md

593: Update travis build url to travis-ci.com.

---

behat.yml.dist
composer.json
features/api.feature
features/d8.feature
features/i18n/es/d8.feature

Some strings on the page were changed in Drupal 9.4

Drupal core default theme changed to Olivero

---

.github/workflows/ci.yml
features/bootstrap/FeatureContext.php

Test on PHP 8.2

---

.readthedocs.yaml

close #648 
Add a .readthedocs.yml configuration file #648 
please let me know if any additional modifications are required.

added readthedocs.yaml file

---

features/backend_login.feature
features/bootstrap/FeatureContext.php
src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php
src/Drupal/DrupalExtension/ServiceContainer/DrupalExtension.php

Fixes Issue #680: Logout bug drupal 10.3.x

---

src/Drupal/DrupalExtension/ServiceContainer/DrupalExtension.php

Issue #493 - Allow to add extra entries to the text and selectors i behat.yml.

Issue #493 - 5.x Allow to add extra entries to the text and selectors
